/*  数据库：health*/
create database health;

use health;

/*  用户表 user： */
create table user(
id int(11) not null auto_increment,
username varchar(64) not null,
pwd varchar(100) not null,
email varchar(60) not null,
age int(5) not null,
name varchar(64) not null,
type tinyint not null, /* 1表示普通用户，2表示系统管理员*/
date datetime not null,
primary key (id));


/*  测试主题表 subject:  */
create table subject(
id int(11) not null  auto_increment,
subject varchar(300) not null,
remark varchar(800) not null,
primary key (id));

/*  测试选项表 choice:  */
create table choice(
id int(11) not null auto_increment,
sid int(11) not null,
cid int(11) not null,
title varchar(300) not null,
ch0 varchar(200) not null,
ch1 varchar(200) not null,
ch2 varchar(200) not null,
ch3 varchar(200),
ch4 varchar(200),
ch5 varchar(200),
ch6 varchar(200),
ch7 varchar(200),
ch8 varchar(200),
ch9 varchar(200),
ch10 varchar(200),
primary key (id));

/*  测试选项分值表score:  */
create table score(
id int(11) not null auto_increment,
sid int(11) not null,
cid int(11) not null,
code int(11) not null,
choice varchar(200) not null,
score int(11) not null,
primary key (id));

/*  用户测试记录表 record:   */
create table record(
id int(11) not null auto_increment,
sid int(11) not null,
uid int(11) not null,
score float(11) not null,
date datetime not null,
primary key (id));



insert into user(username,pwd,email,age,name,type,date) values('antong','123456','antong@sohu.com','18','安彤','2','');
insert into user(username,pwd,email,age,name,type,date) values('antong0','123456','antong@sohu.com','18','安彤','1','');
insert into user(username,pwd,email,age,name,type,date) values('antong1','123456','antong@sohu.com','18','安彤','1','');
insert into user(username,pwd,email,age,name,type,date) values('antong2','123456','antong@sohu.com','18','安彤','1','');
insert into user(username,pwd,email,age,name,type,date) values('antong3','123456','antong@sohu.com','18','安彤','1','');
insert into user(username,pwd,email,age,name,type,date) values('antong4','123456','antong@sohu.com','18','安彤','1','');
insert into user(username,pwd,email,age,name,type,date) values('antong5','123456','antong@sohu.com','18','安彤','1','');
insert into user(username,pwd,email,age,name,type,date) values('antong6','123456','antong@sohu.com','18','安彤','1','');
insert into user(username,pwd,email,age,name,type,date) values('antong7','123456','antong@sohu.com','18','安彤','1','');
insert into user(username,pwd,email,age,name,type,date) values('antong8','123456','antong@sohu.com','18','安彤','1','');
insert into user(username,pwd,email,age,name,type,date) values('antong9','123456','antong@sohu.com','18','安彤','1','');

insert into subject(subject,remark) values('你是否了解你的自尊水平？','请仔细阅读每一条，根据你一贯的实际表现选择符合你实际情况的描述。');
insert into subject(subject,remark) values('你是否了解你的自信水平？','请仔细阅读每一条，根据你一贯的实际表现选择符合你实际情况的描述。');
insert into subject(subject,remark) values('你是否能够把握好谨慎与鲁莽的度？','请仔细阅读下面24个问题，挑选出你认为合适的答案。当不能决定选择“是”或“否”的时候，请选“不知道”。');
insert into subject(subject,remark) values('你是否感觉到幸福？','以下问题涉及到你近期对生活的感受与看法，无好坏之分，根据自己的现实情况和切身体验回答，并请你仔细阅读每道题目，选择相应的答案。');
insert into subject(subject,remark) values('你对你的生活是否满意？','下面的一些陈述涉及人们对生活的不同感受。请阅读下列陈述，如果你同意该观点，请选择“同意”；如果不同意该观点，请选择“不同意”；如果无法肯定是否同意，则选择“？”。请务必回答每一个问题。');

insert into choice(sid,cid,title,ch0,ch1,ch2,ch3) values('1','1','我感到我是一个有价值的人，至少与其他人在同一水平上','非常符合','符合','不符合','很不符合');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3) values('1','2','我感到我有许多好的品质','非常符合','符合','不符合','很不符合');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3) values('1','3','归根结底，我倾向于觉得自己是一个失败者','非常符合','符合','不符合','很不符合');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3) values('1','4','我能像大多数人一样把事情做好','非常符合','符合','不符合','很不符合');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3) values('1','5','我感到自己值得自豪的地方不多','非常符合','符合','不符合','很不符合');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3) values('1','6','我对自己持肯定态度','非常符合','符合','不符合','很不符合');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3) values('1','7','总的来说，我对自己是满意的','非常符合','符合','不符合','很不符合');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3) values('1','8','我希望我能为自己获得更多尊重','非常符合','符合','不符合','很不符合');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3) values('1','9','我确实时常感到毫无用处','非常符合','符合','不符合','很不符合');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3) values('1','10','我时常认为自己一无是处','非常符合','符合','不符合','很不符合');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3,ch4) values('2','5','我觉得与其他人相比，自己精力不足，积极性不高','从不','偶尔','有时','经常','总是');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3,ch4) values('2','6','我很想知道，我的全部想法是否合适','从不','偶尔','有时','经常','总是');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3,ch4) values('2','7','我担心自己受人愚弄了','从不','偶尔','有时','经常','总是');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3,ch4) values('2','8','我觉得别人的样貌比我漂亮','从不','偶尔','有时','经常','总是');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3,ch4) values('2','9','陌生人面前讲话，我拘束的很','从不','偶尔','有时','经常','总是');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3,ch4) values('2','10','任务交给我办会出错','从不','偶尔','有时','经常','总是');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3,ch4) values('2','11','我希望学会在他人面前谈笑自若','从不','偶尔','有时','经常','总是');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3,ch4) values('2','12','我希望有更大的自信心','从不','偶尔','有时','经常','总是');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3,ch4) values('2','13','我想知道怎么做才能赢得别人更多的好感','从不','偶尔','有时','经常','总是');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3,ch4) values('2','14','我过分谦虚','从不','偶尔','有时','经常','总是');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3,ch4) values('2','15','我过于自负','从不','偶尔','有时','经常','总是');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3,ch4) values('2','16','很多人的意见与我不同','从不','偶尔','有时','经常','总是');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3,ch4) values('2','17','我觉得周围没有一个能向他诉说我个人私事的人','从不','偶尔','有时','经常','总是');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3,ch4) values('2','18','人们对我的希望过大','从不','偶尔','有时','经常','总是');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3,ch4) values('2','19','我觉得人们对我的成就没有引起足够的兴趣','从不','偶尔','有时','经常','总是');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3,ch4) values('2','20','我觉得自己陷入窘境','从不','偶尔','有时','经常','总是');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3,ch4) values('2','21','我觉得大多数人不理解我','从不','偶尔','有时','经常','总是');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3,ch4) values('2','22','我对周围无安全感','从不','偶尔','有时','经常','总是');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3,ch4) values('2','23','我常有不必要的担心','从不','偶尔','有时','经常','总是');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3,ch4) values('2','24','我走进满屋是人的房间时，觉得很不自然','从不','偶尔','有时','经常','总是');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3,ch4) values('2','25','我觉得有人背后议论我','从不','偶尔','有时','经常','总是');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3,ch4) values('2','26','我感到身心不能放松','从不','偶尔','有时','经常','总是');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3,ch4) values('2','27','我觉得别人做任何事比我容易','从不','偶尔','有时','经常','总是');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3,ch4) values('2','28','我害怕有什么不幸的事会降落到我头上','从不','偶尔','有时','经常','总是');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3,ch4) values('2','29','我会考虑别人用什么方式对待我','从不','偶尔','有时','经常','总是');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3,ch4) values('2','30','我希望自己善于交际','从不','偶尔','有时','经常','总是');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3,ch4) values('2','31','只有我确信自己是正确的，才敢在讨论会上发言','从不','偶尔','有时','经常','总是');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3,ch4) values('2','32','别人对我有什么希望','从不','偶尔','有时','经常','总是');
insert into choice(sid,cid,title,ch0,ch1,ch2) values('3','1','一个冬天的周末，你计划开车旅游，天气突然变坏，下起大雪。你还会按计划旅游吗？','是','否','不知道');
insert into choice(sid,cid,title,ch0,ch1,ch2) values('3','2','你学过系统的飞行知识，但未经实地训练，你敢单独驾滑翔机飞行吗？','是','否','不知道');
insert into choice(sid,cid,title,ch0,ch1,ch2) values('3','3','高塔没有扶手，你敢攀登吗？','是','否','不知道');
insert into choice(sid,cid,title,ch0,ch1,ch2) values('3','4','你运气好，偶然一次买彩票中了奖，下次你会买更多吗？','是','否','不知道');
insert into choice(sid,cid,title,ch0,ch1,ch2) values('3','5','在洗澡间使用电器，你从不担心吗？','是','否','不知道');
insert into choice(sid,cid,title,ch0,ch1,ch2) values('3','6','你喝了酒，已有醉意，还敢骑自行车行路吗？','是','否','不知道');
insert into choice(sid,cid,title,ch0,ch1,ch2) values('3','7','如果你有汽车，你是否平时不检修，只进行定期大修？','是','否','不知道');
insert into choice(sid,cid,title,ch0,ch1,ch2) values('3','8','你是个司机，会在能见度不足百分之百的情况下超车吗？','是','否','不知道');
insert into choice(sid,cid,title,ch0,ch1,ch2) values('3','9','你会毫不犹豫就参加乘气球越过一座高山的活动吗？','是','否','不知道');
insert into choice(sid,cid,title,ch0,ch1,ch2) values('3','10','你敢抚摸已经麻醉的狮子吗？','是','否','不知道');
insert into choice(sid,cid,title,ch0,ch1,ch2) values('3','11','你认为躺在床上吸烟不危险吗？','是','否','不知道');
insert into choice(sid,cid,title,ch0,ch1,ch2) values('3','12','你认为在大河上漂流探险有意义吗？','是','否','不知道');
insert into choice(sid,cid,title,ch0,ch1,ch2) values('3','13','你一冲动，就会鲁莽从事吗？','是','否','不知道');
insert into choice(sid,cid,title,ch0,ch1,ch2) values('3','14','你是个司机，虽然路途不熟，但是为了节省30分钟，你就会抄近路行使吗？','是','否','不知道');
insert into choice(sid,cid,title,ch0,ch1,ch2) values('3','15','你不会游泳，如果有人出100元赏金，你会从3米高的跳台上跳下水吗？','是','否','不知道');
insert into choice(sid,cid,title,ch0,ch1,ch2) values('3','16','如果你临时有事要出门，可衣服没有洗完，你会让洗衣机继续转动吗？','是','否','不知道');
insert into choice(sid,cid,title,ch0,ch1,ch2) values('3','17','你认为家里面安放灭火器没有必要吗？','是','否','不知道');
insert into choice(sid,cid,title,ch0,ch1,ch2) values('3','18','你认为摩托车考试没有必要吗？','是','否','不知道');
insert into choice(sid,cid,title,ch0,ch1,ch2) values('3','19','黄灯亮了，你还会领小孩一起过马路吗？','是','否','不知道');
insert into choice(sid,cid,title,ch0,ch1,ch2) values('3','20','你主张在汽车里不用安全带吗？','是','否','不知道');
insert into choice(sid,cid,title,ch0,ch1,ch2) values('3','21','你通常不阅读产品用法说明书，是吗？','是','否','不知道');
insert into choice(sid,cid,title,ch0,ch1,ch2) values('3','22','你一遇急事，就不顾交通规则吗？','是','否','不知道');
insert into choice(sid,cid,title,ch0,ch1,ch2) values('3','23','你想为朋友买件衬衫，但忘了尺寸，你还会买吗？','是','否','不知道');
insert into choice(sid,cid,title,ch0,ch1,ch2) values('3','24','你眼看就要攀登到山顶了，但风暴马上就要来临，你会迅速登上山顶，然后再返回去吗？','是','否','不知道');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3,ch4,ch5) values('4','1','你的总体感觉怎样（在过去的一个月里）？','好极了','精神很好','精神不错','精神时好时坏','精神不好','精神很不好');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3,ch4) values('4','2','你是否为自己的神经质或“神经病”感到烦恼（在过去的一个月里）？','极端烦恼','相当烦恼','有些烦恼','很少烦恼','一点也不烦恼');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3,ch4,ch5) values('4','3','你是否一直牢牢地控制着自己的行为、思维、情感或感觉（在过去的一个月里）？','绝对的','大部分是的','一般来说是的','控制得不太好','有些混乱','非常混乱');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3,ch4,ch5) values('4','4','你是否由于悲哀、失去信心、失望或有许多麻烦而怀疑没有任何事情值得去做（在过去的一个月里）？','极端怀疑','非常怀疑','相当怀疑','有些怀疑','略微怀疑','一点也不怀疑');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3,ch4) values('4','5','你是否正在受到或曾经受到任何约束、刺激或压力（在过去的一个月里）？','相当多','不少','有些','不多','没有');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3,ch4) values('4','6','你的生活是否幸福、满足或愉快（在过去的一个月里）？','非常幸福','相当幸福','满足','略有些不满足','非常不满足');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3,ch4) values('4','7','你是否有理由怀疑自己曾经失去理智、或对行为、谈话、思维或记忆失去控制（在过去的一个月里）？','一点也没有','只有一点点','不严重','有些严重','非常严重');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3,ch4,ch5) values('4','8','你是否感到焦虑、担心或不安（在过去的一个月里）？','极端严重','非常严重','相当严重','有些','很少','无');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3,ch4,ch5) values('4','9','你睡醒之后是否感到头脑清晰和精力充沛（在过去的一个月里）？','天天如此','几乎天天','相当频繁','不多','很少','无');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3,ch4,ch5) values('4','10','你是否因为疾病、身体的不适、疼痛或对患病的恐惧而烦恼（在过去的一个月里）？','所有的时间','大部分时间','很多时间','有时','偶尔','无');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3,ch4,ch5) values('4','11','你每天的生活中是否充满了让你感兴趣的事情（在过去的一个月里）？','所有的时间','大部分时间','很多时间','有时','偶尔','无');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3,ch4,ch5) values('4','12','你是否感到沮丧和忧郁（在过去的一个月里）？','所有的时间','大部分时间','很多时间','有时','偶尔','无');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3,ch4,ch5) values('4','13','你是否情绪稳定并能把握住自己（在过去的一个月里）？','所有的时间','大部分时间','很多时间','有时','偶尔','无');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3,ch4,ch5) values('4','14','你是否感到疲劳、过累、无力或筋疲力竭（在过去的一个月里）？','所有的时间','大部分时间','很多时间','有时','偶尔','无');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3,ch4,ch5,ch6,ch7,ch8,ch9,ch10) values('4','15','你对自己健康关心或担忧的程度如何（在过去的一个月里）？','10（表示不关心）','9','8','7','6','5','4','3','2','1','0（表示非常关心）');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3,ch4,ch5,ch6,ch7,ch8,ch9,ch10) values('4','16','你感到放松或紧张的程度如何（在过去的一个月里）？','10（表示松弛）','9','8','7','6','5','4','3','2','1','0（表示紧张）');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3,ch4,ch5,ch6,ch7,ch8,ch9,ch10) values('4','17','你感觉自己的精力、精神和活力如何（在过去的一个月里）？','0（表示无精打采）','1','2','3','4','5','6','7','8','9','10（表示精力充沛）');
insert into choice(sid,cid,title,ch0,ch1,ch2,ch3,ch4,ch5,ch6,ch7,ch8,ch9,ch10) values('4','18','你忧郁或快乐的程度如何（在过去的一个月里）？','0（表示非常忧郁）','1','2','3','4','5','6','7','8','9','10（表示非常快乐）');

insert into choice(sid,cid,title,ch0,ch1,ch2) values('5','1','当我老了以后发现事情似乎要比原先想象得好','不同意','？','同意');
insert into choice(sid,cid,title,ch0,ch1,ch2) values('5','2','与我所认识的多数人相比，我更好地把握了生活中的机遇','不同意','？','同意');
insert into choice(sid,cid,title,ch0,ch1,ch2) values('5','3','现在是我一生中最沉闷的时期','不同意','？','同意');
insert into choice(sid,cid,title,ch0,ch1,ch2) values('5','4','我现在和年轻时一样幸福','不同意','？','同意');
insert into choice(sid,cid,title,ch0,ch1,ch2) values('5','5','我的生活原本应该是更好的时光','不同意','？','同意');
insert into choice(sid,cid,title,ch0,ch1,ch2) values('5','6','现在是我一生中最美好的时光','不同意','？','同意');
insert into choice(sid,cid,title,ch0,ch1,ch2) values('5','7','我所做的事多半是令人厌烦和单调乏味的','不同意','？','同意');
insert into choice(sid,cid,title,ch0,ch1,ch2) values('5','8','我估计最近能遇到一些有趣的令人愉快的事','不同意','？','同意');
insert into choice(sid,cid,title,ch0,ch1,ch2) values('5','9','我现在做的事和以前做的事一样有趣','不同意','？','同意');
insert into choice(sid,cid,title,ch0,ch1,ch2) values('5','10','我感到老了、有些累了','不同意','？','同意');
insert into choice(sid,cid,title,ch0,ch1,ch2) values('5','11','我感到自己确实上了年纪，但我并不为此而烦恼','不同意','？','同意');
insert into choice(sid,cid,title,ch0,ch1,ch2) values('5','12','回首往事，我想当满足','不同意','？','同意');
insert into choice(sid,cid,title,ch0,ch1,ch2) values('5','13','即使能改变自己的过去，我也不愿有所改变','不同意','？','同意');
insert into choice(sid,cid,title,ch0,ch1,ch2) values('5','14','与其他同龄人相比，我曾做出过较多的愚蠢的决定','不同意','？','同意');
insert into choice(sid,cid,title,ch0,ch1,ch2) values('5','15','与其他同龄人相比，我的外表较年轻','不同意','？','同意');
insert into choice(sid,cid,title,ch0,ch1,ch2) values('5','16','我已经为一个月甚至一年后该做的事制定了计划','不同意','？','同意');
insert into choice(sid,cid,title,ch0,ch1,ch2) values('5','17','回首往事，我有许多想得到的东西均未得到','不同意','？','同意');
insert into choice(sid,cid,title,ch0,ch1,ch2) values('5','18','与其他人相比，我惨遭失败的次数太多了','不同意','？','同意');
insert into choice(sid,cid,title,ch0,ch1,ch2) values('5','19','我在生活中得到了相当多我所期望的东西','不同意','？','同意');
insert into choice(sid,cid,title,ch0,ch1,ch2) values('5','20','不管人们怎样说，许多普通人是越过越糟，而不是越过越好了','不同意','？','同意');

insert into score(sid,cid,choice,score) values(1,4,1,'非常符合',1);
insert into score(sid,cid,code,choice,score) values(1,4,2,'符合',2);
insert into score(sid,cid,code,choice,score) values(1,4,3,'不符合',3);
insert into score(sid,cid,code,choice,score) values(1,4,4,'非常不符合',4);
insert into score(sid,cid,code,choice,score) values(1,5,1,'非常符合',4);
insert into score(sid,cid,code,choice,score) values(1,5,2,'符合',3);
insert into score(sid,cid,code,choice,score) values(1,5,3,'不符合',2);
insert into score(sid,cid,code,choice,score) values(1,5,4,'非常不符合',1);
insert into score(sid,cid,code,choice,score) values(1,6,1,'非常符合',1);
insert into score(sid,cid,code,choice,score) values(1,6,2,'符合',2);
insert into score(sid,cid,code,choice,score) values(1,6,3,'不符合',3);
insert into score(sid,cid,code,choice,score) values(1,6,4,'非常不符合',4);
insert into score(sid,cid,code,choice,score) values(1,7,1,'非常符合',1);
insert into score(sid,cid,code,choice,score) values(1,7,2,'符合',2);
insert into score(sid,cid,code,choice,score) values(1,7,3,'不符合',3);
insert into score(sid,cid,code,choice,score) values(1,7,4,'非常不符合',4);
insert into score(sid,cid,code,choice,score) values(1,8,1,'非常符合',1);
insert into score(sid,cid,code,choice,score) values(1,8,2,'符合',2);
insert into score(sid,cid,code,choice,score) values(1,8,3,'不符合',3);
insert into score(sid,cid,code,choice,score) values(1,8,4,'非常不符合',4);
insert into score(sid,cid,code,choice,score) values(1,9,1,'非常符合',4);
insert into score(sid,cid,code,choice,score) values(1,9,2,'符合',3);
insert into score(sid,cid,code,choice,score) values(1,9,3,'不符合',2);
insert into score(sid,cid,code,choice,score) values(1,9,4,'非常不符合',1);
insert into score(sid,cid,code,choice,score) values(1,10,1,'非常符合',4);
insert into score(sid,cid,code,choice,score) values(1,10,2,'符合',3);
insert into score(sid,cid,code,choice,score) values(1,10,3,'不符合',2);
insert into score(sid,cid,code,choice,score) values(1,10,4,'非常不符合',1);
insert into score(sid,cid,choice,score) values(2,2,'从不',0);
insert into score(sid,cid,choice,score) values(2,2,'偶尔',1);
insert into score(sid,cid,choice,score) values(2,2,'有时',2);
insert into score(sid,cid,choice,score) values(2,2,'经常',3);
insert into score(sid,cid,choice,score) values(2,2,'总是',4);
insert into score(sid,cid,choice,score) values(2,3,'从不',0);
insert into score(sid,cid,choice,score) values(2,3,'偶尔',1);
insert into score(sid,cid,choice,score) values(2,3,'有时',2);
insert into score(sid,cid,choice,score) values(2,3,'经常',3);
insert into score(sid,cid,choice,score) values(2,3,'总是',4);
insert into score(sid,cid,choice,score) values(2,4,'从不',0);
insert into score(sid,cid,choice,score) values(2,4,'偶尔',1);
insert into score(sid,cid,choice,score) values(2,4,'有时',2);
insert into score(sid,cid,choice,score) values(2,4,'经常',3);
insert into score(sid,cid,choice,score) values(2,4,'总是',4);
insert into score(sid,cid,choice,score) values(2,5,'从不',0);
insert into score(sid,cid,choice,score) values(2,5,'偶尔',1);
insert into score(sid,cid,choice,score) values(2,5,'有时',2);
insert into score(sid,cid,choice,score) values(2,5,'经常',3);
insert into score(sid,cid,choice,score) values(2,5,'总是',4);
insert into score(sid,cid,choice,score) values(2,6,'从不',0);
insert into score(sid,cid,choice,score) values(2,6,'偶尔',1);
insert into score(sid,cid,choice,score) values(2,6,'有时',2);
insert into score(sid,cid,choice,score) values(2,6,'经常',3);
insert into score(sid,cid,choice,score) values(2,6,'总是',4);
insert into score(sid,cid,choice,score) values(2,7,'从不',0);
insert into score(sid,cid,choice,score) values(2,7,'偶尔',1);
insert into score(sid,cid,choice,score) values(2,7,'有时',2);
insert into score(sid,cid,choice,score) values(2,7,'经常',3);
insert into score(sid,cid,choice,score) values(2,7,'总是',4);
insert into score(sid,cid,choice,score) values(2,8,'从不',0);
insert into score(sid,cid,choice,score) values(2,8,'偶尔',1);
insert into score(sid,cid,choice,score) values(2,8,'有时',2);
insert into score(sid,cid,choice,score) values(2,8,'经常',3);
insert into score(sid,cid,choice,score) values(2,8,'总是',4);
insert into score(sid,cid,choice,score) values(2,9,'从不',0);
insert into score(sid,cid,choice,score) values(2,9,'偶尔',1);
insert into score(sid,cid,choice,score) values(2,9,'有时',2);
insert into score(sid,cid,choice,score) values(2,9,'经常',3);
insert into score(sid,cid,choice,score) values(2,9,'总是',4);
insert into score(sid,cid,choice,score) values(2,10,'从不',0);
insert into score(sid,cid,choice,score) values(2,10,'偶尔',1);
insert into score(sid,cid,choice,score) values(2,10,'有时',2);
insert into score(sid,cid,choice,score) values(2,10,'经常',3);
insert into score(sid,cid,choice,score) values(2,10,'总是',4);
insert into score(sid,cid,choice,score) values(2,11,'从不',0);
insert into score(sid,cid,choice,score) values(2,11,'偶尔',1);
insert into score(sid,cid,choice,score) values(2,11,'有时',2);
insert into score(sid,cid,choice,score) values(2,11,'经常',3);
insert into score(sid,cid,choice,score) values(2,11,'总是',4);
insert into score(sid,cid,choice,score) values(2,12,'从不',0);
insert into score(sid,cid,choice,score) values(2,12,'偶尔',1);
insert into score(sid,cid,choice,score) values(2,12,'有时',2);
insert into score(sid,cid,choice,score) values(2,12,'经常',3);
insert into score(sid,cid,choice,score) values(2,12,'总是',4);
insert into score(sid,cid,choice,score) values(2,13,'从不',0);
insert into score(sid,cid,choice,score) values(2,13,'偶尔',1);
insert into score(sid,cid,choice,score) values(2,13,'有时',2);
insert into score(sid,cid,choice,score) values(2,13,'经常',3);
insert into score(sid,cid,choice,score) values(2,13,'总是',4);
insert into score(sid,cid,choice,score) values(2,14,'从不',0);
insert into score(sid,cid,choice,score) values(2,14,'偶尔',1);
insert into score(sid,cid,choice,score) values(2,14,'有时',2);
insert into score(sid,cid,choice,score) values(2,14,'经常',3);
insert into score(sid,cid,choice,score) values(2,14,'总是',4);
insert into score(sid,cid,choice,score) values(2,15,'从不',0);
insert into score(sid,cid,choice,score) values(2,15,'偶尔',1);
insert into score(sid,cid,choice,score) values(2,15,'有时',2);
insert into score(sid,cid,choice,score) values(2,15,'经常',3);
insert into score(sid,cid,choice,score) values(2,15,'总是',4);
insert into score(sid,cid,choice,score) values(2,16,'从不',0);
insert into score(sid,cid,choice,score) values(2,16,'偶尔',1);
insert into score(sid,cid,choice,score) values(2,16,'有时',2);
insert into score(sid,cid,choice,score) values(2,16,'经常',3);
insert into score(sid,cid,choice,score) values(2,16,'总是',4);
insert into score(sid,cid,choice,score) values(2,17,'从不',0);
insert into score(sid,cid,choice,score) values(2,17,'偶尔',1);
insert into score(sid,cid,choice,score) values(2,17,'有时',2);
insert into score(sid,cid,choice,score) values(2,17,'经常',3);
insert into score(sid,cid,choice,score) values(2,17,'总是',4);
insert into score(sid,cid,choice,score) values(2,18,'从不',0);
insert into score(sid,cid,choice,score) values(2,18,'偶尔',1);
insert into score(sid,cid,choice,score) values(2,18,'有时',2);
insert into score(sid,cid,choice,score) values(2,18,'经常',3);
insert into score(sid,cid,choice,score) values(2,18,'总是',4);
insert into score(sid,cid,choice,score) values(2,19,'从不',0);
insert into score(sid,cid,choice,score) values(2,19,'偶尔',1);
insert into score(sid,cid,choice,score) values(2,19,'有时',2);
insert into score(sid,cid,choice,score) values(2,19,'经常',3);
insert into score(sid,cid,choice,score) values(2,19,'总是',4);
insert into score(sid,cid,choice,score) values(2,20,'从不',0);
insert into score(sid,cid,choice,score) values(2,20,'偶尔',1);
insert into score(sid,cid,choice,score) values(2,20,'有时',2);
insert into score(sid,cid,choice,score) values(2,20,'经常',3);
insert into score(sid,cid,choice,score) values(2,20,'总是',4);
insert into score(sid,cid,choice,score) values(2,21,'从不',0);
insert into score(sid,cid,choice,score) values(2,21,'偶尔',1);
insert into score(sid,cid,choice,score) values(2,21,'有时',2);
insert into score(sid,cid,choice,score) values(2,21,'经常',3);
insert into score(sid,cid,choice,score) values(2,21,'总是',4);
insert into score(sid,cid,choice,score) values(2,22,'从不',0);
insert into score(sid,cid,choice,score) values(2,22,'偶尔',1);
insert into score(sid,cid,choice,score) values(2,22,'有时',2);
insert into score(sid,cid,choice,score) values(2,22,'经常',3);
insert into score(sid,cid,choice,score) values(2,22,'总是',4);
insert into score(sid,cid,choice,score) values(2,23,'从不',0);
insert into score(sid,cid,choice,score) values(2,23,'偶尔',1);
insert into score(sid,cid,choice,score) values(2,23,'有时',2);
insert into score(sid,cid,choice,score) values(2,23,'经常',3);
insert into score(sid,cid,choice,score) values(2,23,'总是',4);
insert into score(sid,cid,choice,score) values(2,24,'从不',0);
insert into score(sid,cid,choice,score) values(2,24,'偶尔',1);
insert into score(sid,cid,choice,score) values(2,24,'有时',2);
insert into score(sid,cid,choice,score) values(2,24,'经常',3);
insert into score(sid,cid,choice,score) values(2,24,'总是',4);
insert into score(sid,cid,choice,score) values(2,25,'从不',0);
insert into score(sid,cid,choice,score) values(2,25,'偶尔',1);
insert into score(sid,cid,choice,score) values(2,25,'有时',2);
insert into score(sid,cid,choice,score) values(2,25,'经常',3);
insert into score(sid,cid,choice,score) values(2,25,'总是',4);
insert into score(sid,cid,choice,score) values(2,26,'从不',0);
insert into score(sid,cid,choice,score) values(2,26,'偶尔',1);
insert into score(sid,cid,choice,score) values(2,26,'有时',2);
insert into score(sid,cid,choice,score) values(2,26,'经常',3);
insert into score(sid,cid,choice,score) values(2,26,'总是',4);
insert into score(sid,cid,choice,score) values(2,27,'从不',0);
insert into score(sid,cid,choice,score) values(2,27,'偶尔',1);
insert into score(sid,cid,choice,score) values(2,27,'有时',2);
insert into score(sid,cid,choice,score) values(2,27,'经常',3);
insert into score(sid,cid,choice,score) values(2,27,'总是',4);
insert into score(sid,cid,choice,score) values(2,28,'从不',0);
insert into score(sid,cid,choice,score) values(2,28,'偶尔',1);
insert into score(sid,cid,choice,score) values(2,28,'有时',2);
insert into score(sid,cid,choice,score) values(2,28,'经常',3);
insert into score(sid,cid,choice,score) values(2,28,'总是',4);
insert into score(sid,cid,choice,score) values(2,29,'从不',0);
insert into score(sid,cid,choice,score) values(2,29,'偶尔',1);
insert into score(sid,cid,choice,score) values(2,29,'有时',2);
insert into score(sid,cid,choice,score) values(2,29,'经常',3);
insert into score(sid,cid,choice,score) values(2,29,'总是',4);
insert into score(sid,cid,choice,score) values(2,30,'从不',0);
insert into score(sid,cid,choice,score) values(2,30,'偶尔',1);
insert into score(sid,cid,choice,score) values(2,30,'有时',2);
insert into score(sid,cid,choice,score) values(2,30,'经常',3);
insert into score(sid,cid,choice,score) values(2,30,'总是',4);
insert into score(sid,cid,choice,score) values(2,31,'从不',0);
insert into score(sid,cid,choice,score) values(2,31,'偶尔',1);
insert into score(sid,cid,choice,score) values(2,31,'有时',2);
insert into score(sid,cid,choice,score) values(2,31,'经常',3);
insert into score(sid,cid,choice,score) values(2,31,'总是',4);
insert into score(sid,cid,choice,score) values(2,32,'从不',0);
insert into score(sid,cid,choice,score) values(2,32,'偶尔',1);
insert into score(sid,cid,choice,score) values(2,32,'有时',2);
insert into score(sid,cid,choice,score) values(2,32,'经常',3);
insert into score(sid,cid,choice,score) values(2,32,'总是',4);

insert into score(sid,cid,choice,score) values(3,1,'是',0);
insert into score(sid,cid,choice,score) values(3,1,'否',2);
insert into score(sid,cid,choice,score) values(3,1,'不知道',1);
insert into score(sid,cid,choice,score) values(3,2,'是',0);
insert into score(sid,cid,choice,score) values(3,2,'否',2);
insert into score(sid,cid,choice,score) values(3,2,'不知道',1);
insert into score(sid,cid,choice,score) values(3,3,'是',0);
insert into score(sid,cid,choice,score) values(3,3,'否',2);
insert into score(sid,cid,choice,score) values(3,3,'不知道',1);
insert into score(sid,cid,choice,score) values(3,4,'是',0);
insert into score(sid,cid,choice,score) values(3,4,'否',2);
insert into score(sid,cid,choice,score) values(3,4,'不知道',1);
insert into score(sid,cid,choice,score) values(3,5,'是',0);
insert into score(sid,cid,choice,score) values(3,5,'否',2);
insert into score(sid,cid,choice,score) values(3,5,'不知道',1);
insert into score(sid,cid,choice,score) values(3,6,'是',0);
insert into score(sid,cid,choice,score) values(3,6,'否',2);
insert into score(sid,cid,choice,score) values(3,6,'不知道',1);
insert into score(sid,cid,choice,score) values(3,7,'是',0);
insert into score(sid,cid,choice,score) values(3,7,'否',2);
insert into score(sid,cid,choice,score) values(3,7,'不知道',1);
insert into score(sid,cid,choice,score) values(3,8,'是',0);
insert into score(sid,cid,choice,score) values(3,8,'否',2);
insert into score(sid,cid,choice,score) values(3,8,'不知道',1);
insert into score(sid,cid,choice,score) values(3,9,'是',0);
insert into score(sid,cid,choice,score) values(3,9,'否',2);
insert into score(sid,cid,choice,score) values(3,9,'不知道',1);
insert into score(sid,cid,choice,score) values(3,10,'是',0);
insert into score(sid,cid,choice,score) values(3,10,'否',2);
insert into score(sid,cid,choice,score) values(3,10,'不知道',1);
insert into score(sid,cid,choice,score) values(3,11,'是',0);
insert into score(sid,cid,choice,score) values(3,11,'否',2);
insert into score(sid,cid,choice,score) values(3,11,'不知道',1);
insert into score(sid,cid,choice,score) values(3,12,'是',0);
insert into score(sid,cid,choice,score) values(3,12,'否',2);
insert into score(sid,cid,choice,score) values(3,12,'不知道',1);
insert into score(sid,cid,choice,score) values(3,13,'是',0);
insert into score(sid,cid,choice,score) values(3,13,'否',2);
insert into score(sid,cid,choice,score) values(3,13,'不知道',1);
insert into score(sid,cid,choice,score) values(3,14,'是',0);
insert into score(sid,cid,choice,score) values(3,14,'否',2);
insert into score(sid,cid,choice,score) values(3,14,'不知道',1);
insert into score(sid,cid,choice,score) values(3,15,'是',0);
insert into score(sid,cid,choice,score) values(3,15,'否',2);
insert into score(sid,cid,choice,score) values(3,15,'不知道',1);
insert into score(sid,cid,choice,score) values(3,16,'是',0);
insert into score(sid,cid,choice,score) values(3,16,'否',2);
insert into score(sid,cid,choice,score) values(3,16,'不知道',1);
insert into score(sid,cid,choice,score) values(3,17,'是',0);
insert into score(sid,cid,choice,score) values(3,17,'否',2);
insert into score(sid,cid,choice,score) values(3,17,'不知道',1);
insert into score(sid,cid,choice,score) values(3,18,'是',0);
insert into score(sid,cid,choice,score) values(3,18,'否',2);
insert into score(sid,cid,choice,score) values(3,18,'不知道',1);
insert into score(sid,cid,choice,score) values(3,19,'是',0);
insert into score(sid,cid,choice,score) values(3,19,'否',2);
insert into score(sid,cid,choice,score) values(3,19,'不知道',1);
insert into score(sid,cid,choice,score) values(3,20,'是',0);
insert into score(sid,cid,choice,score) values(3,20,'否',2);
insert into score(sid,cid,choice,score) values(3,20,'不知道',1);
insert into score(sid,cid,choice,score) values(3,21,'是',0);
insert into score(sid,cid,choice,score) values(3,21,'否',2);
insert into score(sid,cid,choice,score) values(3,21,'不知道',1);
insert into score(sid,cid,choice,score) values(3,22,'是',0);
insert into score(sid,cid,choice,score) values(3,22,'否',2);
insert into score(sid,cid,choice,score) values(3,22,'不知道',1);
insert into score(sid,cid,choice,score) values(3,23,'是',0);
insert into score(sid,cid,choice,score) values(3,23,'否',2);
insert into score(sid,cid,choice,score) values(3,23,'不知道',1);
insert into score(sid,cid,choice,score) values(3,24,'是',0);
insert into score(sid,cid,choice,score) values(3,24,'否',2);
insert into score(sid,cid,choice,score) values(3,24,'不知道',1);
insert into score(sid,cid,choice,score) values(4,1,'好极了',6);
insert into score(sid,cid,choice,score) values(4,1,'精神很好',5);
insert into score(sid,cid,choice,score) values(4,1,'精神不错',4);
insert into score(sid,cid,choice,score) values(4,1,'精神时好时坏',3);
insert into score(sid,cid,choice,score) values(4,1,'精神不好',2);
insert into score(sid,cid,choice,score) values(4,1,'精神很不好',1);
insert into score(sid,cid,choice,score) values(4,2,'极端烦恼',1);
insert into score(sid,cid,choice,score) values(4,2,'相当烦恼',2);
insert into score(sid,cid,choice,score) values(4,2,'有些烦恼',3);
insert into score(sid,cid,choice,score) values(4,2,'很少烦恼',4);
insert into score(sid,cid,choice,score) values(4,2,'一点也不烦恼',5);
insert into score(sid,cid,choice,score) values(4,3,'绝对的',1);
insert into score(sid,cid,choice,score) values(4,3,'大部分是的',2);
insert into score(sid,cid,choice,score) values(4,3,'一般来说是的',3);
insert into score(sid,cid,choice,score) values(4,3,'控制得不太好',4);
insert into score(sid,cid,choice,score) values(4,3,'有些混乱',5);
insert into score(sid,cid,choice,score) values(4,3,'非常混乱',6);
insert into score(sid,cid,choice,score) values(4,4,'极端怀疑',1);
insert into score(sid,cid,choice,score) values(4,4,'非常怀疑',2);
insert into score(sid,cid,choice,score) values(4,4,'相当怀疑',3);
insert into score(sid,cid,choice,score) values(4,4,'有些怀疑',4);
insert into score(sid,cid,choice,score) values(4,4,'略微怀疑',5);
insert into score(sid,cid,choice,score) values(4,4,'一点也不怀疑',6);
insert into score(sid,cid,choice,score) values(4,5,'相当多',1);
insert into score(sid,cid,choice,score) values(4,5,'不少',2);
insert into score(sid,cid,choice,score) values(4,5,'有些',3);
insert into score(sid,cid,choice,score) values(4,5,'不多',4);
insert into score(sid,cid,choice,score) values(4,5,'没有',5);
insert into score(sid,cid,choice,score) values(4,6,'非常幸福',5);
insert into score(sid,cid,choice,score) values(4,6,'相当幸福',4);
insert into score(sid,cid,choice,score) values(4,6,'满足',3);
insert into score(sid,cid,choice,score) values(4,6,'略有些不满足',2);
insert into score(sid,cid,choice,score) values(4,6,'非常不满足',1);
insert into score(sid,cid,choice,score) values(4,7,'一点也没有',5);
insert into score(sid,cid,choice,score) values(4,7,'只有一点点',4);
insert into score(sid,cid,choice,score) values(4,7,'不严重',3);
insert into score(sid,cid,choice,score) values(4,7,'有些严重',2);
insert into score(sid,cid,choice,score) values(4,7,'非常严重',1);
insert into score(sid,cid,choice,score) values(4,8,'极端严重',1);
insert into score(sid,cid,choice,score) values(4,8,'非常严重',2);
insert into score(sid,cid,choice,score) values(4,8,'相当严重',3);
insert into score(sid,cid,choice,score) values(4,8,'有些',4);
insert into score(sid,cid,choice,score) values(4,8,'很少',5);
insert into score(sid,cid,choice,score) values(4,8,'无',6);
insert into score(sid,cid,choice,score) values(4,9,'天天如此',6);
insert into score(sid,cid,choice,score) values(4,9,'几乎天天',5);
insert into score(sid,cid,choice,score) values(4,9,'相当频繁',4);
insert into score(sid,cid,choice,score) values(4,9,'不多',3);
insert into score(sid,cid,choice,score) values(4,9,'很少',2);
insert into score(sid,cid,choice,score) values(4,9,'无',1);
insert into score(sid,cid,choice,score) values(4,10,'所有的时间',1);
insert into score(sid,cid,choice,score) values(4,10,'大部分时间',2);
insert into score(sid,cid,choice,score) values(4,10,'很多时间',3);
insert into score(sid,cid,choice,score) values(4,10,'有时',4);
insert into score(sid,cid,choice,score) values(4,10,'偶尔',5);
insert into score(sid,cid,choice,score) values(4,10,'无',6);
insert into score(sid,cid,choice,score) values(4,11,'所有的时间',6);
insert into score(sid,cid,choice,score) values(4,11,'大部分时间',5);
insert into score(sid,cid,choice,score) values(4,11,'很多时间',4);
insert into score(sid,cid,choice,score) values(4,11,'有时',3);
insert into score(sid,cid,choice,score) values(4,11,'偶尔',2);
insert into score(sid,cid,choice,score) values(4,11,'无',1);
insert into score(sid,cid,choice,score) values(4,12,'所有的时间',1);
insert into score(sid,cid,choice,score) values(4,12,'大部分时间',2);
insert into score(sid,cid,choice,score) values(4,12,'很多时间',3);
insert into score(sid,cid,choice,score) values(4,12,'有时',4);
insert into score(sid,cid,choice,score) values(4,12,'偶尔',5);
insert into score(sid,cid,choice,score) values(4,12,'无',6);
insert into score(sid,cid,choice,score) values(4,13,'所有的时间',6);
insert into score(sid,cid,choice,score) values(4,13,'大部分时间',5);
insert into score(sid,cid,choice,score) values(4,13,'很多时间',4);
insert into score(sid,cid,choice,score) values(4,13,'有时',3);
insert into score(sid,cid,choice,score) values(4,13,'偶尔',2);
insert into score(sid,cid,choice,score) values(4,13,'无',1);
insert into score(sid,cid,choice,score) values(4,14,'所有的时间',1);
insert into score(sid,cid,choice,score) values(4,14,'大部分时间',2);
insert into score(sid,cid,choice,score) values(4,14,'很多时间',3);
insert into score(sid,cid,choice,score) values(4,14,'有时',4);
insert into score(sid,cid,choice,score) values(4,14,'偶尔',5);
insert into score(sid,cid,choice,score) values(4,14,'无',6);
insert into score(sid,cid,choice,score) values(4,15,'10（表示不关心）',10);
insert into score(sid,cid,choice,score) values(4,15,'9',9);
insert into score(sid,cid,choice,score) values(4,15,'8',8);
insert into score(sid,cid,choice,score) values(4,15,'7',7);
insert into score(sid,cid,choice,score) values(4,15,'6',6);
insert into score(sid,cid,choice,score) values(4,15,'5',5);
insert into score(sid,cid,choice,score) values(4,15,'4',4);
insert into score(sid,cid,choice,score) values(4,15,'3',3);
insert into score(sid,cid,choice,score) values(4,15,'2',2);
insert into score(sid,cid,choice,score) values(4,15,'1',1);
insert into score(sid,cid,choice,score) values(4,15,'0（表示非常关心）',0);
insert into score(sid,cid,choice,score) values(4,16,'10（表示松弛）',10);
insert into score(sid,cid,choice,score) values(4,16,'9',9);
insert into score(sid,cid,choice,score) values(4,16,'8',8);
insert into score(sid,cid,choice,score) values(4,16,'7',7);
insert into score(sid,cid,choice,score) values(4,16,'6',6);
insert into score(sid,cid,choice,score) values(4,16,'5',5);
insert into score(sid,cid,choice,score) values(4,16,'4',4);
insert into score(sid,cid,choice,score) values(4,16,'3',3);
insert into score(sid,cid,choice,score) values(4,16,'2',2);
insert into score(sid,cid,choice,score) values(4,16,'1',1);
insert into score(sid,cid,choice,score) values(4,16,'0（表示紧张）',0);
insert into score(sid,cid,choice,score) values(4,17,'0（表示无精打采）',0);
insert into score(sid,cid,choice,score) values(4,17,'1',1);
insert into score(sid,cid,choice,score) values(4,17,'2',2);
insert into score(sid,cid,choice,score) values(4,17,'3',3);
insert into score(sid,cid,choice,score) values(4,17,'4',4);
insert into score(sid,cid,choice,score) values(4,17,'5',5);
insert into score(sid,cid,choice,score) values(4,17,'6',6);
insert into score(sid,cid,choice,score) values(4,17,'7',7);
insert into score(sid,cid,choice,score) values(4,17,'8',8);
insert into score(sid,cid,choice,score) values(4,17,'9',9);
insert into score(sid,cid,choice,score) values(4,17,'10（表示精力充沛）',10);
insert into score(sid,cid,choice,score) values(4,18,'0（表示非常忧郁）',0);
insert into score(sid,cid,choice,score) values(4,18,'1',1);
insert into score(sid,cid,choice,score) values(4,18,'2',2);
insert into score(sid,cid,choice,score) values(4,18,'3',3);
insert into score(sid,cid,choice,score) values(4,18,'4',4);
insert into score(sid,cid,choice,score) values(4,18,'5',5);
insert into score(sid,cid,choice,score) values(4,18,'6',6);
insert into score(sid,cid,choice,score) values(4,18,'7',7);
insert into score(sid,cid,choice,score) values(4,18,'8',8);
insert into score(sid,cid,choice,score) values(4,18,'9',9);
insert into score(sid,cid,choice,score) values(4,18,'10（表示非常快乐）',10);
insert into score(sid,cid,choice,score) values(5,1,'不同意',1);
insert into score(sid,cid,choice,score) values(5,1,'？',2);
insert into score(sid,cid,choice,score) values(5,1,'同意',3);
insert into score(sid,cid,choice,score) values(5,2,'不同意',1);
insert into score(sid,cid,choice,score) values(5,2,'？',2);
insert into score(sid,cid,choice,score) values(5,2,'同意',3);
insert into score(sid,cid,choice,score) values(5,3,'不同意',3);
insert into score(sid,cid,choice,score) values(5,3,'？',2);
insert into score(sid,cid,choice,score) values(5,3,'同意',1);
insert into score(sid,cid,choice,score) values(5,4,'不同意',1);
insert into score(sid,cid,choice,score) values(5,4,'？',2);
insert into score(sid,cid,choice,score) values(5,4,'同意',3);
insert into score(sid,cid,choice,score) values(5,5,'不同意',3);
insert into score(sid,cid,choice,score) values(5,5,'？',2);
insert into score(sid,cid,choice,score) values(5,5,'同意',1);
insert into score(sid,cid,choice,score) values(5,6,'不同意',1);
insert into score(sid,cid,choice,score) values(5,6,'？',2);
insert into score(sid,cid,choice,score) values(5,6,'同意',3);
insert into score(sid,cid,choice,score) values(5,7,'不同意',3);
insert into score(sid,cid,choice,score) values(5,7,'？',2);
insert into score(sid,cid,choice,score) values(5,7,'同意',1);
insert into score(sid,cid,choice,score) values(5,8,'不同意',1);
insert into score(sid,cid,choice,score) values(5,8,'？',2);
insert into score(sid,cid,choice,score) values(5,8,'同意',3);
insert into score(sid,cid,choice,score) values(5,9,'不同意',1);
insert into score(sid,cid,choice,score) values(5,9,'？',2);
insert into score(sid,cid,choice,score) values(5,9,'同意',3);
insert into score(sid,cid,choice,score) values(5,10,'不同意',3);
insert into score(sid,cid,choice,score) values(5,10,'？',2);
insert into score(sid,cid,choice,score) values(5,10,'同意',1);
insert into score(sid,cid,choice,score) values(5,11,'不同意',1);
insert into score(sid,cid,choice,score) values(5,11,'？',2);
insert into score(sid,cid,choice,score) values(5,11,'同意',3);
insert into score(sid,cid,choice,score) values(5,12,'不同意',1);
insert into score(sid,cid,choice,score) values(5,12,'？',2);
insert into score(sid,cid,choice,score) values(5,12,'同意',3);
insert into score(sid,cid,choice,score) values(5,13,'不同意',1);
insert into score(sid,cid,choice,score) values(5,13,'？',2);
insert into score(sid,cid,choice,score) values(5,13,'同意',3);
insert into score(sid,cid,choice,score) values(5,14,'不同意',3);
insert into score(sid,cid,choice,score) values(5,14,'？',2);
insert into score(sid,cid,choice,score) values(5,14,'同意',1);
insert into score(sid,cid,choice,score) values(5,15,'不同意',1);
insert into score(sid,cid,choice,score) values(5,15,'？',2);
insert into score(sid,cid,choice,score) values(5,15,'同意',3);
insert into score(sid,cid,choice,score) values(5,16,'不同意',1);
insert into score(sid,cid,choice,score) values(5,16,'？',2);
insert into score(sid,cid,choice,score) values(5,16,'同意',3);
insert into score(sid,cid,choice,score) values(5,17,'不同意',3);
insert into score(sid,cid,choice,score) values(5,17,'？',2);
insert into score(sid,cid,choice,score) values(5,17,'同意',1);
insert into score(sid,cid,choice,score) values(5,18,'不同意',3);
insert into score(sid,cid,choice,score) values(5,18,'？',2);
insert into score(sid,cid,choice,score) values(5,18,'同意',1);
insert into score(sid,cid,choice,score) values(5,19,'不同意',1);
insert into score(sid,cid,choice,score) values(5,19,'？',2);
insert into score(sid,cid,choice,score) values(5,19,'同意',3);
insert into score(sid,cid,choice,score) values(5,20,'不同意',3);
insert into score(sid,cid,choice,score) values(5,20,'？',2);
insert into score(sid,cid,choice,score) values(5,20,'同意',1);